# 登录主机用户名和密码
ansible_ssh_user: 'root'
ansible_ssh_pass: 'secret'
ansible_ssh_port: 22

ntp_type: chrony # or ntp
# 设置同步时间服务器
ntp_servers:
  - 'ntp.cloud.aliyuncs.com'
  - 'ntp.aliyun.com'
  - 'ntp1.aliyun.com'
  - 'ntp1.cloud.aliyuncs.com'
  - 'ntp2.aliyun.com'
  - 'ntp2.cloud.aliyuncs.com'
  - 'ntp3.aliyun.com'
  - 'ntp3.cloud.aliyuncs.com'
  - 'ntp4.aliyun.com'
  - 'ntp4.cloud.aliyuncs.com'
  - 'ntp5.aliyun.com'
  - 'ntp5.cloud.aliyuncs.com'
  - 'ntp6.aliyun.com'
  - 'ntp6.cloud.aliyuncs.com'
  - 'ntp7.cloud.aliyuncs.com'
  - 'ntp8.cloud.aliyuncs.com'
  - 'ntp9.cloud.aliyuncs.com'
  - 'ntpupdate.tencentyun.com'

TimeZone: 'Asia/Shanghai'
kernel: !!bool false               # true: 升级内核   false: 不升级内核

kubelet:
  swap: false                      # true: 不关闭swap  false: 关闭swap

ssh:
  hardening: !!bool true           # true: 开启ssh加固   false: 禁止ssh加固
  Port: 22
  ClientAliveInterval: 600         # 10分钟无操作断开连接
  MaxAuthTries: 3
  PasswordAuthentication: 'yes'
  PubkeyAuthentication: 'yes'


docker:
  version: '19.03' # choose the version of docker
#  Environments:
#    - HTTP_PROXY=http://127.0.0.1:8080
  dataDir: /var/lib/docker
  execOpts:
    - 'native.cgroupdriver=systemd'
  registryMirrors:
    - https://fz5yth0r.mirror.aliyuncs.com
    - https://dockerhub.mirrors.nwafu.edu.cn
    - https://docker.mirrors.ustc.edu.cn/
    - https://reg-mirror.qiniu.com
    - http://hub-mirror.c.163.com/
    - https://registry.docker-cn.com
#  insecureRegistries:
#    - 100.64.2.52:9999
#    - 100.64.1.31:9999


pip:
  registry: https://pypi.doubanio.com/simple/


redis:
  thp_type: 'never'     # 禁用透明大页  always madvise never




