---
  
- hosts: mongo
  gather_facts: yes

  # https://www.mongodb.com/docs/v4.4/tutorial/convert-standalone-to-replica-set/?_ga=2.125791619.842481179.1656902131-551625923.1656663184&_gac=1.150795588.1656663187.Cj0KCQjwtvqVBhCVARIsAFUxcRsvMIr0ft4o8hthI1wNdpUQ1EarX97f55-g4m0DR8ou8kn8NPOG8WUaAiDUEALw_wcB
  vars:
    mongodb_net_bindip: 0.0.0.0
    mongodb_security_authorization: "enabled"
    mongodb_replication_replset: rsdemo
    mongodb_users:
      - {
        name: testuser,
        password: passw0rd,
        roles: readWrite,
        database: development
    }
    mongodb_oplog_users:
      - {
        user: oplog,
        password: passw0rd
    }
    mongodb_login_host: 192.168.60.8
    # host_type can be replica(default) and arbiter
    mongodb_replication_params:
      - {
          host_name: 192.168.60.8,
          host_port: "{{ mongodb_net_port }}",
          host_type: replica,
        }

  roles:
    - mongodb
  tags:
    - mongodb


