---

- hosts: zookeeper_nodes
  gather_facts: yes

  vars:
    - zookeeper_version: 3.7.1
    - zookeeper_data_dir: /data/zookeeper/data
    - zookeeper_data_log_dir: /data/zookeeper/logs
    - zookeeper_environment:
        JVMFLAGS: "-Xms512m -Xmx1024m"

  roles:
    - role: openjdk
      openjdk_app: jdk
      openjdk_ver:
        major: 11
        minor: 0
        patch: 8
        b: 10
    - zookeeper
  tags:
    - zookeeper



