---
# tasks file for initos

- name: "[InitOS] Set timezone"
  timezone:
    name: "{{ TimeZone }}"
  when: TimeZone is defined

- name: "[InitOS] 修改fstab文件关闭swap"
  lineinfile:
    dest: /etc/fstab
    regexp: "(^\\s*[^#].+swap)"
    line: '#\1'
    backrefs: yes
  when: swap_switch

- name: "[InitOS] 分发modules-load和sysctl的conf"
  copy:
    src: files/{{ item.src }}
    dest: "{{ item.dest }}"
    mode: g=r,o=r
  with_items:
    #- { src: 'k8s-ipvs.conf', dest: "/etc/modules-load.d/" }
    - { src: 'limits.conf', dest: "/etc/security/limits.d/" }

- name: "[InitOS] Send sysctl file"
  template:
    src: sysctl.conf.j2
    #dest: /etc/sysctl.d/k8s-sysctl.conf
    dest: /etc/sysctl.d/sysctl.conf
    mode: g=r,o=r

- name: "[InitOS] 临时关闭 selinux"
  shell: "setenforce 0"
  failed_when: false

- name: "[InitOS] 永久关闭 selinux"
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

# 修改console连接提示
- name: "[InitOS] 分发issue"
  copy:
    src: files/{{ item.src }}
    dest: "{{ item.dest }}"
    mode: g=r,o=r
  with_items:
    - { src: 'issue', dest: "/etc/" }

- name: "[InitOS] 分发issue.net"
  copy:
    src: files/{{ item.src }}
    dest: "{{ item.dest }}"
    mode: g=r,o=r
  with_items:
    - { src: 'issue', dest: "/etc/issue.net" }

# 修改ssh连接提示
- name: "[InitOS] 分发motd"
  copy:
    src: files/{{ item.src }}
    dest: "{{ item.dest }}"
    mode: g=r,o=r
  with_items:
    - { src: 'motd', dest: "/etc/" }

- name: "[InitOS] enable --now systemd-modules-load"
  systemd:
    name: systemd-modules-load
    state: started
    enabled: yes

- name: "[InitOS] 设置crond开机并启动"
  systemd: name=crond enabled=yes

- name: "[InitOS] Set hostname"
  hostname: name={{ hostname }}
  when: hostname is defined and hostname






