---
- name: "[InitOS] 关闭firewalld NetworkManager dnsmasq - CentOS"
  systemd: 
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - firewalld
    - NetworkManager
    - postfix
    - dnsmasq
  ignore_errors: True

# 优化设置 journal 日志相关，避免日志重复搜集，浪费系统资源
- name: "[InitOS] 禁止rsyslog获取journald日志"
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: "{{ item }}"
    line: '#\1'
    backrefs: yes
  with_items:
  - '(^\$ModLoad imjournal)'
  - '(^\$IMJournalStateFile)'

- name: "[InitOS] 修改systemctl启动的最小文件打开数量"
  lineinfile:
    dest: /etc/systemd/system.conf
    state: present
    regexp: "^#{{ item.key }}"
    line: "\\1={{ item.value }}"
    backrefs: yes
  with_items:
  - { key: '(DefaultLimitCORE)=', value: '{{ system_default_limit_core }}' }
  - { key: '(DefaultLimitNOFILE)=', value: '{{ system_default_limit_nofile }}' }


#- name: "[InitOS] 创建repo备份目录"
#  file:
#    path: /etc/yum.repo.d/bak
#    state: directory
#
#- name: "[InitOS] 备份repo"
#  shell: mv /etc/yum.repo.d/*.repo /etc/yum.repo.d/bak

- name: "[InitOS] CentOS 7/RHEL 7 添加系统源"
  shell: |
    sed -e 's|^mirrorlist=|#mirrorlist=|g' \
        -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g' \
        -i.bak \
        /etc/yum.repos.d/CentOS-*.repo
  when: ansible_distribution_major_version == '7'

- name: "[InitOS] CentOS 8/RHEL 8 添加系统源"
  shell: |
    sed -e 's|^mirrorlist=|#mirrorlist=|g' \
        -e 's|^#baseurl=http://mirror.centos.org/$contentdir|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos|g' \
        -i.bak \
        /etc/yum.repos.d/CentOS-*.repo
  when: ansible_distribution_major_version == '8'

- name: "[InitOS] 添加EPEL仓库"
  yum: name=epel-release state=latest update_cache=yes

- name: "[InitOS] 安装基础软件包"
  yum: 
    name: 
      - conntrack-tools     # ipvs 模式需要
      - psmisc        # 安装psmisc 才能使用命令killall
      #- nfs-utils     # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - jq                  # 轻量JSON处理程序，安装docker查询镜像需要
      - socat               # 用于port forwarding
      - bash-completion     # bash命令补全工具，需要重新登录服务器生效
      - ipset
      - perl           # 内核依赖
      - ipvsadm
      - iptables
      - conntrack
      - libseccomp
      - net-tools
      - crontabs
      - sysstat
      - unzip
      - bind-utils
      - tcpdump
      - telnet
      - lsof
      - nload
      - strace
      - bridge-utils
      - iftop
      - htop
      - wget
      - psmisc
      - chrony
      - tar
      - vim
    state: latest
    update_cache: yes


- block:
    - name: "[InitOS] 导入GPG key"
      rpm_key:
        state: present
        key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    
    - name: "[InitOS] 导入elrepo"
      yum:
        name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
        state: present
    
    - name: "[InitOS] 升级到最新内核"
      yum:
        name: 
          #- kernel-ml
          - kernel-lt
          #- kernel-ml-devel
          - kernel-lt-devel
        disablerepo: "*"
        enablerepo: "elrepo-kernel"
    
    - name: "[InitOS] 修改默认启动内核到新内核"
      shell: grub2-set-default  0 && grub2-mkconfig -o /etc/grub2.cfg
  when: kernel
  tags:
    - kernel

- name: "[InitOS] 设置内核参数适应docker"
  shell: |
    grubby --args="user_namespace.enable=1" --update-kernel=$(grubby --default-kernel)

- name: "[InitOS] 物理机下调整cpu到非省电模式"
  command: tuned-adm profile throughput-performance
  when: ansible_virtualization_role == 'host'


- name: "[InitOS] 更新系统"
  yum:
    name: '*'
    update_cache: yes
    state: latest
  tags:
    - update_os

