---
# tasks file for initos

- include_tasks: common.yml

- include_tasks: config_{{ ansible_os_family }}.yml
  when: ansible_os_family == "RedHat"

- include_tasks: chrony.yml

- include_tasks: ssh.yml

- name: Reboot host
  shell: sleep 2 && shutdown -r now "reboot"
  async: 1
  poll: 0
  ignore_errors: yes
  tags:
    - reboot



