---
# tasks file for initos

- include_tasks: centos.yml
  when: ansible_os_family == "RedHat"

- name: Set timezone
  timezone: name="{{ TimeZone }}"
  when: TimeZone is defined

- name: 修改fstab文件关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: "(^\\s*[^#].+swap)"
    line: '#\1'
    backrefs: yes
  when: not kubelet.swap

- name: 分发modules-load和sysctl的conf
  copy:
    src: files/{{ item.src }}
    dest: "{{ item.dest }}"
    mode: g=r,o=r
  with_items:
    #- { src: 'k8s-ipvs.conf', dest: "/etc/modules-load.d/" }
    - { src: 'limits.conf', dest: "/etc/security/limits.d/" }

- name: Send sysctl file
  template:
    src: sysctl.conf.j2
    #dest: /etc/sysctl.d/k8s-sysctl.conf
    dest: /etc/sysctl.d/sysctl.conf
    mode: g=r,o=r

- name: enable --now systemd-modules-load
  systemd: name=systemd-modules-load state=started enabled=yes


- name: generate chrony config file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  when: ntp_type == "chrony"

#- include_tasks: time/chrony.yml
#  when: ntp_type == "chrony"

- name: generate ntp config file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  when: ntp_type != "chrony"

#- include_tasks: time/ntp.yml
#  when: ntp_type != "chrony"

- name: 设置crond开机并启动
  systemd: name=crond enabled=yes


- include_tasks: ssh.yml

#- name: 关闭ssh反向解析
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    regexp: "^#UseDNS"
#    line: "UseDNS no"
#
#- name: 修改ssh监听端口
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    regexp: "^#Port"
#    line: "Port {{ ssh.port | default(22) }}"
#
#- name: 修改ssh日志级别
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    regexp: "^#LogLevel"
#    line: "Port {{ ssh.loglevel }}"

#- name: prepare some dirs
#  file: name={{ item }} state=directory
#  with_items:
#  - /etc/kubernetes/pki
#  - /etc/kubernetes/manifests
#  - /var/log/kubernetes

- name: Set hostname
  hostname: name={{ hostname }}
  when: hostname is defined and hostname

- name: Reboot host
  shell: sleep 2 && shutdown -r now "reboot"
  async: 1
  poll: 0
  ignore_errors: yes
  tags:
    - reboot



