---
- name: "[RabbitMQ] Add RabbitMQ repository file [RHEL/CentOS]"
  template:
    src: "{{ rabbitmq_rpm_repo_tpl }}"
    dest: "/etc/yum.repos.d/{{ rabbitmq_rpm_repo_tpl | basename | regex_replace('\\.j2$', '') }}"
    force: true
    mode: 0644
    backup: true

- name: "[RabbitMQ] Install RabbitMQ [RHEL/CentOS]"
  yum:
    name: "rabbitmq-server{{ rabbitmq_series_rpm_version | ternary ('-' + (rabbitmq_series_rpm_version | string),'-' + (rabbitmq_series | string) + '*') }}"
    state: present
    disablerepo: "{{ rabbitmq_rpm_disable_repo | d(omit, true) }}"
    enablerepo: "{{ rabbitmq_rpm_enable_repo | d(omit, true) }}"

#- name: 创建目录
#  file:
#    path: "{{ item }}"
#    state: directory
#    owner: rabbitmq
#    group: rabbitmq
#  with_items:
#    - "{{ RABBITMQ_MNESIA_BASE }}"
#    - "{{ RABBITMQ_LOG_BASE }}"
#  when:
#    - RABBITMQ_MNESIA_BASE is defined or RABBITMQ_LOG_BASE is defined


- name: 创建目录
  file:
    path: "{{ item }}"
    state: directory
    owner: rabbitmq
    group: rabbitmq
  loop:
    - "{{ RABBITMQ_MNESIA_BASE }}"
    - "{{ RABBITMQ_LOG_BASE }}"
  when:
    - RABBITMQ_MNESIA_BASE is defined or RABBITMQ_LOG_BASE is defined

