---
# tasks file for adduser

- name: Add group "{{ MYUSER }}"
  group:
    name: "{{ MYUSER }}"
    state: present
    system: yes

- name: add the user deploy and set a primary group of 'deploy'
  user:
    name: "{{ MYUSER }}"
    group: "{{ MYUSER }}"
    create_home: True
    system: True
    comment: devops
    shell: /bin/bash
    password: "{{ MYPWD | password_hash('sha512') }}"


#- name: Set authorized key
#  authorized_key:
#    user: "{{ MYUSER }}"
#    state: present
#    key: "{{ lookup('file', '/home/ansible/files/pubkey/id_rsa.pub') }}"
