---

mongodb_package: mongodb-org
mongodb_package_state: present
mongodb_version: "4.4"
mongodb_apt_key_from_url: false
mongodb_apt_keyserver: 'hkp://keyserver.ubuntu.com:80'
mongodb_apt_key_id:
  "3.6": "2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
  "4.0": "9DA31620334BD75D9DCB49F368818C72E52529D4"
  "4.2": "E162F504A20CDF15827F718D4B7C549A058F8B6B"
  "4.4": "20691eec35216c63caf66ce1656408e390cfb1f5"
mongodb_apt_key_url:
  "3.6": "https://www.mongodb.org/static/pgp/server-3.6.asc"
  "4.0": "https://www.mongodb.org/static/pgp/server-4.0.asc"
  "4.2": "https://www.mongodb.org/static/pgp/server-4.2.asc"
  "4.4": "https://www.mongodb.org/static/pgp/server-4.4.asc"

mongodb_pymongo_from_pip: true                   # Install latest PyMongo via PIP or package manager
mongodb_pymongo_pip_version: 3.12.3

mongodb_user_update_password: "on_create"        # MongoDB user password update default policy
mongodb_manage_service: true
mongodb_manage_systemd_unit: true
mongodb_systemd_unit_limit_nofile: 64000
mongodb_systemd_unit_limit_nproc: 64000

mongodb_disable_transparent_hugepages: false

mongodb_use_numa: true

mongodb_user: "{{ 'mongod' if ('RedHat' == ansible_os_family) else 'mongodb' }}"
mongodb_uid:
mongodb_gid:
mongodb_daemon_name: "{{ 'mongod' if ('mongodb-org' in mongodb_package) else 'mongodb' }}"

## net Options
mongodb_net_bindip: 127.0.0.1                    # Comma separated list of ip addresses to listen on
mongodb_net_http_enabled: false                  # Enable http interface
mongodb_net_ipv6: false                          # Enable IPv6 support (disabled by default)
mongodb_net_maxconns: 65536                      # Max number of simultaneous connections
mongodb_net_port: 27017                          # Specify port number
mongodb_net_ssl: disabled                        # Enable or disable ssl connections
mongodb_net_ssl_mode: ""                         # Set the ssl mode (RequireSSL / preferSSL / AllowSSL / disabled)
mongodb_net_ssl_pemfile: ""                      # Location of the pemfile to use for ssl
mongodb_net_ssl_host: ""                         # Valid ssl hostname

## processManagement Options
# Fork server process
# Enabled by default for RedHat as the init scripts assume forking is enabled.
mongodb_processmanagement_fork: "{{ 'RedHat' == ansible_os_family }}"

## security Options
# Disable or enable security. Possible values: 'disabled', 'enabled'
mongodb_security_authorization: "disabled"
mongodb_security_keyfile: /etc/mongodb-keyfile   # Specify path to keyfile with password for inter-process authentication
mongodb_security_javascript_enabled: true        # Enables or disables server-side JavaScript execution

## storage Options
mongodb_storage_dbpath: /data/db                 # Directory for datafiles
mongodb_storage_dirperdb: false                  # Use one directory per DB

# The storage engine for the mongod database
mongodb_storage_engine: "wiredTiger"
# mmapv1 specific options
mongodb_storage_quota_enforced: false            # Limits each database to a certain number of files
mongodb_storage_quota_maxfiles: 8                # Number of quota files per DB
mongodb_storage_smallfiles: false                # Very useful for non-data nodes

mongodb_storage_journal_enabled: true            # Enable journaling
mongodb_storage_prealloc: true                   # Enable data file preallocation

mongodb_wiredtiger_directory_for_indexes: false

## systemLog Options
## The destination to which MongoDB sends all log output. Specify either 'file' or 'syslog'.
## If you specify 'file', you must also specify mongodb_systemlog_path.
mongodb_systemlog_destination: "file"
mongodb_systemlog_logappend: true                                        # Append to logpath instead of over-writing
mongodb_systemlog_logrotate: "rename"                                    # Logrotation behavior
mongodb_systemlog_path: /var/log/mongodb/{{ mongodb_daemon_name }}.log   # Log file to send write to instead of stdout

## operationProfiling Options
mongodb_operation_profiling_slow_op_threshold_ms: 100
mongodb_operation_profiling_mode: "off"

## cloud options (MongoDB >= 4.0)
mongodb_cloud_monitoring_free_state: "runtime"

## replication Options
mongodb_replication_replset: ""                   # Enable replication
mongodb_replication_replindexprefetch: "all"      # specify index prefetching behavior (if secondary) [none|_id_only|all]
mongodb_replication_oplogsize: 1024               # specifies a maximum size in megabytes for the replication operation log

# MMS Agent
mongodb_mms_agent_pkg: https://cloud.mongodb.com/download/agent/monitoring/mongodb-mms-monitoring-agent_7.2.0.488-1_amd64.ubuntu1604.deb
mongodb_mms_group_id: ""
mongodb_mms_api_key: ""
mongodb_mms_base_url: https://mms.mongodb.com

# password for inter-process authentication
# please regenerate this file on production environment with command 'openssl rand -base64 741'
mongodb_keyfile_content: |
  Ac5FupiqXcpXa4tbrq2kNp2NS2oQOrZKqhAi1c/OWSPOYU2+HfBJqJNveKxoIDT2
  CziHaJkQeLvXFBRpvlfyrsMY8qNoOSAzedyiqJHbc2Rf2qO4bEDnRvcQasXt1lXW
  Nj8Lf+nJ3ujKB60HDmbrnYWYQf4Z/y2IuRHhzTktwUfbu1vx4C8OozoU5kVbM7Bm
  nWPs2ugEiA/hbXd8ssOstQhh4Sisry1l23NwnwNQQd5qosOcfRa392xXcAsq3J4b
  DWyGSkKiTnWPrs4iMrwibZkIXnZn939Vu8tmbcSbeA4EDO0sRaYNKyLYQSnh2QIC
  2c5KFRbZ/AmFM20coQmULo66dt66i9nrv/f4OTZjRNtnsCBOImGNyiy0L7roREWT
  6NP5ItjOGf8U4HU18CEfgrt01TfBVeeoiK23v/bP64DXJgRwKeQ1PY8bVx/cMQlX
  flxLH4CEc+1KEu+WT4dcou9V0pzcAM6XC1gZVpZjh2rP85KJwzHUk8mpO4PEmaD7
  DH7QYATx0hJj4kYIchtGNPr5Ukhzg+DydILPV2x1oZZmYLbtvy2hi9xImVGIlvsn
  d2hNTz8Bi60CB2WPuDJ2H0OWGIIG7++1B74ICKZN6sVuMXTTQ5FjbQoDxem/dDEJ
  7RzgkQfY/FWHvgfVd6Hc0oc+mSRgHzPkhRXF9wK4EFbrzpiRMsda70vTtN/KiQBL
  9hTzdTY+2gZspWFz9OQBtFeX+rIGoSNLhwHLnjDb2P5BzF+YIq76tUer3s6FplJR
  bI9OgLLRWKOM+LsxX4Q5o0es7/Rosp7o7/dIxLhebPXV2Lhpe6UV6jbeN0HcmGt9
  HO/RC3LW3lIitf7/NTqJNuu0tau+EEFQQ7sowHdkWuCATMNHUNYrw99PeXIW47rr
  rZN02MU4hTCw9a5AEoXeijwtS6CNhAI7v6oxYDao3cwh4NgGy4qqgEXfW/LuiOAg
  RtgNVCajK3RuAEcIQxcaP8ecjlSQ

# names and passwords for administrative users
mongodb_user_admin_name: siteUserAdmin
mongodb_user_admin_password: passw0rd

mongodb_root_admin_name: siteRootAdmin
mongodb_root_admin_password: passw0rd

mongodb_root_backup_name: backupuser
mongodb_root_backup_password: passw0rd

# setParameter config
mongodb_set_parameters:

# custom config options
mongodb_config:
