---
# 设置主机名
hostname:

timezone: Asia/ShangHai
swap_switch: true  # 默认关闭swap

# 是否要升级内核到最新版本
# false: 不升级
# true: 升级到源中最新的LTS版本,如5.x LTS
kernel: false

##################### 内核参数配置 #########################
kernel_sysrq: 0
kernel_vm_swappiness: 0
kernel_pid_max: 1000000
kernel_net_ipv4_ip_local_port_range: '10000 65500'
# 是否开启内核路由转发,默认不开启
kernel_net_ipv4_ip_forward: false
# 系统级打开最大文件句柄的数量
kernel_fs_file_max: 2097152
# 决定进程级最大打开数量
kernel_fs_nr_open: 2097152
# 开启SYN的cookies，当出现SYN等待队列溢出时，启用cookies进行处理
kernel_net_ipv4_tcp_syncookies: 1
# socket 保持在 FIN_WAIT_2 状态的最大时间
kernel_net_ipv4_tcp_fin_timeout: 1
# 减少TIME_WAIT连接数，避免过多TIME_WAIT连接占用网络资源导致新建连接资源紧张，时延增加
kernel_net_ipv4_tcp_max_tw_buckets: 5000
# 允许将TIME-WAIT的socket重新用于新的TCP连接。如果新请求的时间戳，比存储的时间戳更大，则系统将会从TIME_WAIT状态的存活连接中选取一个，重新分配给新的请求连接
kernel_net_ipv4_tcp_tw_reuse: 1
# TCP发送keepalive探测消息的间隔时间(秒),用于确认TCP连接是否有效。默认7200
kernel_net_ipv4_tcp_keepalive_time: 60
# 确定TCP栈应该如何反映内存使用，每个值的单位都是内存页（通常是4KB）。
# 第一个值是内存使用的下限。
# 第二个值是内存压力模式开始对缓冲区使用应用压力的上限。
# 第三个值是内存使用的上限。在这个层次上可以将报文丢弃，从而减少对内存的使用。对于较大的BDP可以增大这些值（其单位是内存页而不是字节）。
# net.ipv4.tcp_mem =
# 为自动调优定义Socket使用的内存。
# 第一个值是为Socket接收缓冲区分配的最少字节数。
# 第二个值是默认值（该值会被rmem_default覆盖），缓冲区在系统负载不重的情况下可以增长到这个值。
# 第三个值是接收缓冲区空间的最大字节数（该值会被rmem_max覆盖）。
kernel_net_ipv4_tcp_rmem: '1024 4096 16777216'
# 为自动调优定义Socket使用的内存。
# 第一个值是为Socket发送缓冲区分配的最少字节数。
# 第二个值是默认值（该值会被wmem_default覆盖），缓冲区在系统负载不重的情况下可以增长到这个值。
# 第三个值是发送缓冲区空间的最大字节数（该值会被wmem_max覆盖）。
kernel_net_ipv4_tcp_wmem: '1024 4096 16777216'
# 默认的TCP数据接收窗口大小(字节)
kernel_net_core_rmem_default: 262144
# 默认的TCP数据发送窗口大小(字节)
kernel_net_core_wmem_default: 262144
# 最大的TCP数据接收窗口(字节)
kernel_net_core_rmem_max: 16777216
# 最大的TCP数据发送窗口(字节)
kernel_net_core_wmem_max: 16777216
# 表示每个套接字所允许的最大缓冲区的大小
# kernel_net_core_optmem_max: 16777216
# 当内核处理速度比网卡接收速度慢时，这部分多出来的包就会被保存在网卡的接收队列上，而该参数说明了这个队列的数量上限
kernel_net_core_netdev_max_backlog: 262144
# 该参数定义了系统中每一个端口最大的监听队列的长度
kernel_net_core_somaxconn: 65535
# 表示SYN队列的长度，加大队列长度可以容纳更多等待连接的网络连接。
kernel_net_ipv4_tcp_max_syn_backlog: 262144
# nf_conntrack_buckets、nf_conntrack_max参数相关，后者的默认值是前者的4倍，所以一般建议调大nf_conntrack_max参数值。
# ip_conntrack是Linux系统内NAT的一个跟踪连接条目的模块。ip_conntrack模块会使用一个哈希表记录TCP协议“established connection”记录，当这个哈希表满之后，便会导致“nf_conntrack: table full, dropping packet”错误。
# net.nf_conntrack_max = 655350
kernel_net_netfilter_nf_conntrack_max: 655350
kernel_net_netfilter_nf_conntrack_tcp_timeout_established: 1200   # 默认值432000
# kernel_net_netfilter_nf_conntrack_tcp_timeout_time_wait: 30     # 默认值120

# 确保不接受ICMP重定向
kernel_net_ipv4_conf_all_accept_redirects: 0
kernel_net_ipv4_conf_default_accept_redirects: 0
# 确保禁用IP转发
#net.ipv4.ip_forward=0
#net.ipv4.route.flush=1
# 确保不接受secure ICMP重定向
kernel_net_ipv4_conf_all_secure_redirects: 0
kernel_net_ipv4_conf_default_secure_redirects: 0
# 确保记录了可疑数据包
kernel_net_ipv4_conf_all_log_martians: 1
kernel_net_ipv4_conf_default_log_martians: 1
# 确保不接受IPv6路由器通告
kernel_net_ipv6_conf_all_accept_ra: 0
kernel_net_ipv6_conf_default_accept_ra: 0
# 确保不接受IPv6重定向
kernel_net_ipv6_conf_all_accept_redirects: 0
kernel_net_ipv6_conf_default_accept_redirects: 0


# systemctl最小文件和进程打开数量
system_default_limit_core: 100000
system_default_limit_nofile: 100000


##################### SSH参数配置 #########################
# SSH连接安全加固
ssh_hardening: true   # 默认开启安全加固
Port: 22
Protocol: 2
LogLevel: VERBOSE
UseDNS: 'no'
MaxAuthTries: 3
ClientAliveInterval: 600
ClientAliveCountMax: 0
PasswordAuthentication: 'yes'
PubkeyAuthentication: 'yes'
#RSAAuthentication: 'yes'
#RhostsRSAAuthentication: 'no'
IgnoreRhosts: 'yes'
HostbasedAuthentication: 'no'
PermitEmptyPasswords: 'no'
PermitUserEnvironment: 'no'
Ciphers: 'aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'
Banner: /etc/issue.net
MACs: 'hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'
StrictModes: 'yes'
AllowTcpForwarding: 'no'
AllowAgentForwarding: 'no'
X11Forwarding: 'no'
GatewayPorts: 'no'
PermitTunnel: 'no'
KexAlgorithms: 'curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'
HostbasedAcceptedKeytypes: 'ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512'
GSSAPIKexAlgorithms: 'gss-group14-sha256-,gss-group16-sha512-,gss-curve25519-sha256-'
CASignatureAlgorithms: 'ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256'





