# 是否要升级内核到最新版本
# false: 不升级
# true: 升级到源中最新的LTS版本,如5.x LTS
kernel: false

# 设置主机名
hostname:

timezone: Asia/ShangHai
swap_switch: true  # 默认关闭swap

# systemctl最小文件和进程打开数量
system_default_limit_core: 100000
system_default_limit_nofile: 100000

# SSH连接安全加固
ssh_hardening: true   # 默认开启安全加固
Port: 22
Protocol: 2
LogLevel: VERBOSE
UseDNS: 'no'
MaxAuthTries: 3
ClientAliveInterval: 600
ClientAliveCountMax: 0
PasswordAuthentication: 'yes'
PubkeyAuthentication: 'yes'
#RSAAuthentication: 'yes'
#RhostsRSAAuthentication: 'no'
IgnoreRhosts: 'yes'
HostbasedAuthentication: 'no'
PermitEmptyPasswords: 'no'
PermitUserEnvironment: 'no'
Ciphers: 'aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com'
Banner: /etc/issue.net
MACs: 'hmac-sha2-512,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-256-etm@openssh.com'
StrictModes: 'yes'
AllowTcpForwarding: 'no'
AllowAgentForwarding: 'no'
X11Forwarding: 'no'
GatewayPorts: 'no'
PermitTunnel: 'no'
KexAlgorithms: 'curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'
HostbasedAcceptedKeytypes: 'ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512'
GSSAPIKexAlgorithms: 'gss-group14-sha256-,gss-group16-sha512-,gss-curve25519-sha256-'
CASignatureAlgorithms: 'ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-512,rsa-sha2-256'





