---

- name: 检查是否已安装java
  command: command -v java
  ignore_errors: yes
  register: java_bin

- name: 检查是否已设置JAVA_HOME
  command: echo $JAVA_HOME
  #changed_when: false
  ignore_errors: yes
  register: java_home

- fail:
    msg: "未检测到java环境，请先安装java并设置JAVA_HOME后再重新执行"
  when:
    - java_bin.stdout | trim | length < 0
      or java_home.stdout | trim | length < 0


# 设置es内核参数
- name: 设置swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ elasticsearch_vm_swappiness }}"
    state: present

- name: 添加max map count
  sysctl:
    name: vm.max_map_count
    value: "{{ elasticsearch_vm_max_map_count }}"
    state: present

# 设置limits
- name: 配置es soft nofile limits
  lineinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    line: "{{ elasticsearch_users_groups }} soft nofile {{ elasticsearch_nofile_limit }}"

- name: 配置es hard nofile limits
  lineinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    line: "{{ elasticsearch_users_groups }} hard nofile {{ elasticsearch_nofile_limit }}"

- name: 配置es soft noproc limits
  lineinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    line: "{{ elasticsearch_users_groups }} soft nproc {{ elasticsearch_nproc_limit }}"

- name: 配置es hard noproc limits
  lineinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    line: "{{ elasticsearch_users_groups }} hard nporc {{ elasticsearch_nproc_limit }}"

- name: 配置es soft memory limits
  lineinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    line: "{{ elasticsearch_users_groups }} soft memlock unlimited"

- name: 配置es hard memory limits
  lineinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    line: "{{ elasticsearch_users_groups }} hard memlock unlimited"





