---

- name: test if elasticsearch_type is set correctly
  ansible.builtin.assert:
    that:
      - elasticsearch_type is defined
      - elasticsearch_type is string
      - elasticsearch_type in [ "elastic", "oss" ]
      - elasticsearch_series is defined
      - elasticsearch_series_rpm_version is defined
      - elasticsearch_series_deb_version is defined
      - elasticsearch_standalone is defined
      - elasticsearch_rpm_repo_url is defined
      - elasticsearch_rpm_repo_tpl is defined
      - elasticsearch_deb_repo_url is defined
      - elasticsearch_deb_repo_tpl is defined
      - elasticsearch_users_groups is defined
      - elasticsearch_cluster_name is defined
      - elasticsearch_node_name is defined
      #- elasticsearch_node_master is defined
      #- elasticsearch_node_data is defined
      #- elasticsearch_node_ingest is defined
      - elasticsearch_path_data is defined
      - elasticsearch_path_logs is defined
      - elasticsearch_path_repo is defined
      - elasticsearch_path_dump is defined
      - elasticsearch_transport_tcp_port is defined
      - elasticsearch_jvm_heap is defined
      - elasticsearch_vm_swappiness is defined
      - elasticsearch_vm_max_map_count is defined
      - elasticsearch_nofile_limit is defined
      - elasticsearch_nproc_limit is defined
    quiet: yes

- name: "[ElasticSearch] Test that variables are not empty"
  assert:
    that:
      - "{{ item }} != None"
      - "{{ item }} | trim | length > 0"
  with_items:
    - elasticsearch_type
    - elasticsearch_series
    - elasticsearch_standalone
    - elasticsearch_rpm_repo_url
    - elasticsearch_rpm_repo_tpl
    - elasticsearch_deb_repo_url
    - elasticsearch_deb_repo_tpl

- name: test if elasticsearch_network_host is set correctly
  ansible.builtin.assert:
    that:
      - elasticsearch_network_host is defined
      - elasticsearch_network_host is string
    quiet: yes

- name: test if elasticsearch_http_port is set correctly
  ansible.builtin.assert:
    that:
      - elasticsearch_http_port is defined
      - elasticsearch_http_port is number
      - elasticsearch_http_port >=1
      - elasticsearch_http_port <= 65536
    quiet: yes

- name: test if elasticsearch_discovery_seed_hosts is set correctly
  ansible.builtin.assert:
    that:
      - elasticsearch_discovery_seed_hosts is defined
      - elasticsearch_discovery_seed_hosts is iterable
    quiet: yes

- name: test if elasticsearch_cluster_initial_master_nodes is set correctly
  ansible.builtin.assert:
    that:
      - elasticsearch_cluster_initial_master_nodes is defined
      - elasticsearch_cluster_initial_master_nodes is iterable
    quiet: yes




