---
- name: "[ElasticSearch] Add ElasticSearch repository file [RHEL/CentOS]"
  template:
    src: "{{ elasticsearch_rpm_repo_tpl }}"
    dest: "/etc/yum.repos.d/{{ elasticsearch_rpm_repo_tpl | basename | regex_replace('\\.j2$', '') }}"
    force: true
    mode: 0644
    backup: true

- name: "[ElasticSearch] Install ElasticSearch [RHEL/CentOS]"
  yum:
    name: "elasticsearch{{ elasticsearch_series_version | ternary ('-' + (elasticsearch_series_version | string),'-' + (elasticsearch_series | string) + '*') }}"
    state: present
    disablerepo: "{{ elasticsearch_rpm_disable_repo | d(omit, true) }}"
    enablerepo: "{{ elasticsearch_rpm_enable_repo | d(omit, true) }}"
  register: elasticsearch__register_packages
  until: elasticsearch__register_packages is succeeded

- name: 创建目录
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ elasticsearch_users_groups }}"
    group: "{{ elasticsearch_users_groups }}"
  loop:
    - "{{ elasticsearch_path_data }}"
    - "{{ elasticsearch_path_logs }}"
    - "{{ elasticsearch_path_repo }}"
    - "{{ elasticsearch_path_dump }}"
  when:
    - elasticsearch_path_data is defined or elasticsearch_path_logs is defined or elasticsearch_path_repo is defined or elasticsearch_path_dump

- name: 设置开机自启
  systemd:
    name: elasticsearch
    enabled: yes

- command: echo $JAVA_HOME
  #changed_when: false
  ignore_errors: yes
  register: java_home

- name: 设置JAVA_HOME
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    insertafter: EOF
    line: "JAVA_HOME={{ java_home.stdout }}"
  when:
    - elasticsearch_series == 6



